# Generated by Django 3.2.16 on 2023-03-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_auto_20230304_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(default='NO LOCATION', help_text='(e.g: Hegeman Common Room, Barus and Holley Room ###, Zoom, Discord, etc.)', max_length=200, verbose_name='Location during hunt'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=models.CharField(default='-1', max_length=200, verbose_name='Phone number'),
        ),
    ]
