# Generated by Django 3.2.17 on 2024-01-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_auto_20240104_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minorcaseactive',
            options={'verbose_name': 'minor case active', 'verbose_name_plural': 'minor cases active'},
        ),
        migrations.AlterModelOptions(
            name='minorcaseincoming',
            options={'verbose_name': 'minor case incoming', 'verbose_name_plural': 'minor cases incoming'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'round (minor case)', 'verbose_name_plural': 'rounds (minor cases)'},
        ),
        migrations.CreateModel(
            name='MinorCaseCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_datetime', models.DateTimeField(verbose_name='Completed datetime')),
                ('minor_case_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.round', verbose_name='minor case round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'minor case completed',
                'verbose_name_plural': 'minor cases completed',
                'unique_together': {('team', 'minor_case_round')},
            },
        ),
    ]
