# Generated by Django 3.2.17 on 2024-01-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_auto_20240104_0121'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm;'),
    ]
