# Generated by Django 3.2.17 on 2024-01-08 00:47

import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_auto_20240107_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(verbose_name='Transcript')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('audio_url', models.URLField(verbose_name='Audio URL')),
                ('characters', models.TextField(verbose_name='Characters')),
            ],
        ),
        migrations.AlterModelOptions(
            name='minorcaseactive',
            options={'verbose_name': 'minor case active', 'verbose_name_plural': 'minor cases active'},
        ),
        migrations.AlterModelOptions(
            name='minorcaseincoming',
            options={'verbose_name': 'minor case incoming', 'verbose_name_plural': 'minor cases incoming'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'round (minor case)', 'verbose_name_plural': 'rounds (minor cases)'},
        ),
        migrations.AddIndex(
            model_name='voicerecording',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcript'], name='transcript_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
