# Generated by Django 3.2.17 on 2024-02-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_auto_20240109_1528'),
        ('puzzles', '0016_auto_20240207_0314'),
    ]

    operations = [
    ]
