# Generated by Django 3.2.17 on 2024-02-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0017_alter_team_emoji_choice'),
        ('puzzles', '0017_merge_0013_auto_20240109_1528_0016_auto_20240207_0314'),
    ]

    operations = [
    ]
