# Generated by Django 3.2.17 on 2024-02-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_auto_20240114_1508'),
        ('puzzles', '0017_alter_team_emoji_choice'),
    ]

    operations = [
    ]
