# Generated by Django 3.2.17 on 2024-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0017_alter_team_emoji_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="puzzle",
            options={"verbose_name": "puzzle", "verbose_name_plural": "puzzles"},
        ),
        migrations.AlterField(
            model_name="team",
            name="allow_time_unlocks",
            field=models.BooleanField(
                default=True,
                help_text="Whether this team receives time-unlocked puzzles. Note that\n        if disabled, they may be able to access more puzzles by logging out",
                verbose_name="Allow time unlocks",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="is_prerelease_testsolver",
            field=models.BooleanField(
                default=False,
                help_text="Whether this team is a prerelease testsolver. If true, the\n        team will have access to puzzles before the hunt starts",
                verbose_name="Is prerelease testsolver",
            ),
        ),
    ]
