# Generated by Django 3.2.17 on 2024-02-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_merge_20240225_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='desc',
            field=models.CharField(default='', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
