# Generated by Django 3.2.17 on 2024-03-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_auto_20240308_0046'),
        ('puzzles', '0018_merge_20240208_1430'),
    ]

    operations = [
    ]
