# Generated by Django 3.2.17 on 2024-02-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_merge_20240225_1810'),
        ('puzzles', '0019_round_desc'),
    ]

    operations = [
    ]
