# Generated by Django 3.2.17 on 2024-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0019_merge_20240308_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='body_template',
            field=models.CharField(blank=True, help_text='Path of a Markdown file (including .md) under puzzlemarkdown containing the puzzle and\n        solution content, respectively. Defaults to <major-case-slug>/<minor-case-slug>/<puzzle-slug> + ".md" if not\n        specified. All paths are relative to the puzzlemarkdown/ directory as a root.', max_length=255, verbose_name='Body template'),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
