# Generated by Django 3.2.17 on 2024-02-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0021_auto_20240227_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorcaseincomingevent',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration datetime'),
        ),
        migrations.AlterField(
            model_name='minorcaseincomingevent',
            name='final_vote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.minorcasevoteevent', verbose_name='Final vote'),
        ),
        migrations.AlterField(
            model_name='minorcaseincomingevent',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, to='puzzles.MinorCaseVote', verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='minorcasevoteevent',
            name='final_votes',
            field=models.ManyToManyField(blank=True, null=True, to='puzzles.MinorCaseVote', verbose_name='Final votes'),
        ),
    ]
