# Generated by Django 3.2.17 on 2024-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0022_auto_20240227_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorcaseincomingevent',
            name='votes',
            field=models.ManyToManyField(blank=True, to='puzzles.MinorCaseVote', verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='minorcasevoteevent',
            name='final_votes',
            field=models.ManyToManyField(blank=True, to='puzzles.MinorCaseVote', verbose_name='Final votes'),
        ),
    ]
