# Generated by Django 3.2.17 on 2024-03-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_auto_20240308_0046'),
        ('puzzles', '0023_auto_20240227_0300'),
    ]

    operations = [
    ]
