# Generated by Django 3.2.17 on 2024-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0023_auto_20240227_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorcaseincomingevent',
            name='is_initialized',
            field=models.BooleanField(default=False, verbose_name='Is initialized'),
        ),
    ]
