# Generated by Django 3.2.17 on 2024-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0024_merge_0018_auto_20240308_0046_0023_auto_20240227_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erratum',
            name='puzzle_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='desc',
        ),
        migrations.AlterField(
            model_name='erratum',
            name='updates_text',
            field=models.TextField(blank=True, help_text='\n        Text to show on the Updates (errata) page. If blank, it will not appear there.\n        Use $PUZZLE to refer to the puzzle. The text will be prefixed with "On\n        (date)," when displayed, so you should capitalize it the way it would\n        appear mid-sentence. HTML is ok.\n    """\n        ),\n    )\n    puzzle_text = models.TextField(\n        blank=True,\n        verbose_name=_("Puzzle text"),\n        help_text=_(\n            """\n        Text to show on the puzzle page. If blank, it will not appear there.\n        The text will be prefixed with "On (date)," when displayed, so you\n        should capitalize it the way it would appear mid-sentence. HTML is ok.\n    ', verbose_name='Updates text'),
        ),
    ]
