# Generated by Django 3.2.17 on 2024-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0026_auto_20240316_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='body_template',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Markdown-compliant body of the puzzle. This is the main text that will be displayed to the user.', null=True, verbose_name='Puzzle Body'),
        ),
    ]
