# Generated by Django 3.2.17 on 2024-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0027_auto_20240316_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='body_remote',
            field=models.TextField(blank=True, default='', help_text='This is the main text that will be displayed to the user if they are a remote team. (if blank, all users will get regular body.) ', null=True, verbose_name='Remote Puzzle Body'),
        ),
    ]
