# Generated by Django 3.2.17 on 2024-03-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0020_auto_20240316_1716'),
        ('puzzles', '0027_auto_20240316_1902'),
    ]

    operations = [
    ]
