# Generated by Django 3.2.17 on 2024-03-24 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0028_puzzle_body_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcase',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
    ]
