# Generated by Django 3.2.17 on 2024-03-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0028_merge_0020_auto_20240316_1716_0027_auto_20240316_1902"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="body_template",
        ),
        # migrations.DeleteModel(
        #     name='MinorCaseIncoming',
        # ),
    ]
