# Generated by Django 3.2.17 on 2024-03-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0029_auto_20240318_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinorCaseIncoming',
        ),
    ]
