# Generated by Django 3.2.17 on 2024-03-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0029_majorcase_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_major_meta',
            field=models.BooleanField(default=False, verbose_name='Is major meta'),
        ),
        migrations.AlterField(
            model_name='majorcase',
            name='puzzle',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_major_meta': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzle', verbose_name='puzzle'),
        ),
    ]
