# Generated by Django 3.2.17 on 2024-03-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0030_auto_20240323_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzles.round', verbose_name='round'),
        ),
    ]
