# Generated by Django 3.2.17 on 2024-03-24 23:19

import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0031_alter_puzzle_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(verbose_name='Transcript')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('audio_url', models.URLField(verbose_name='Audio URL')),
                ('characters', models.TextField(verbose_name='Characters')),
            ],
        ),
        migrations.AddIndex(
            model_name='voicerecording',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcript'], name='transcript_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
