# Generated by Django 3.2.17 on 2024-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0032_auto_20240324_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicerecording",
            name="search_text",
            field=models.TextField(
                blank=True,
                help_text="Text used for search indexing. Excludes characters named and sound effects",
                null=True,
                verbose_name="Search Text",
            ),
        ),
        migrations.AlterField(
            model_name="voicerecording",
            name="transcript",
            field=models.TextField(blank=True, null=True, verbose_name="Transcript"),
        ),
    ]
