# Generated by Django 3.2.17 on 2024-03-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0033_auto_20240324_2004"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voicerecording",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="voicerecording",
            name="hour",
            field=models.IntegerField(default=0, verbose_name="Recording Hour"),
            preserve_default=False,
        ),
    ]
