# Generated by Django 3.2.17 on 2024-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0034_auto_20240324_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='audio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Audio URL'),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='search_text',
            field=models.TextField(default='', help_text='Text used for search indexing. Excludes characters named and sound effects', verbose_name='Search Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='transcript',
            field=models.TextField(default='', verbose_name='Transcript'),
            preserve_default=False,
        ),
    ]
