# Generated by Django 3.2.17 on 2024-03-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0024_minorcaseincomingevent_is_initialized'),
        ('puzzles', '0035_auto_20240324_2109'),
    ]

    operations = [
    ]
