# Generated by Django 3.2.17 on 2024-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0036_merge_20240330_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorcaseincomingevent',
            name='total_user_votes',
            field=models.IntegerField(default=0, verbose_name='Total user votes'),
        ),
    ]
