# Generated by Django 3.2.17 on 2024-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0038_minorcaseincomingevent_incoming_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorcaseincomingevent',
            name='num_votes_allowed',
            field=models.IntegerField(default=1, verbose_name='Number of votes allowed'),
        ),
    ]
