# Generated by Django 3.2.17 on 2024-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0040_round_unlock_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='brown_team',
            field=models.BooleanField(default=False, help_text='(Undergraduates, Graduates, Faculty, or Alumni)', verbose_name='Brown U Team?'),
        ),
        migrations.AlterField(
            model_name='team',
            name='classroom_need',
            field=models.BooleanField(default=False, help_text='Our availability will be limited, so please do not request one if you can make alternate plans.', verbose_name='Classroom Request?'),
        ),
    ]
