# Generated by Django 3.2.17 on 2024-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0041_auto_20240405_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorcasevoteevent',
            name='selected_case',
        ),
        migrations.AddField(
            model_name='minorcasevoteevent',
            name='selected_cases',
            field=models.ManyToManyField(to='puzzles.Round', verbose_name='Selected minor case(s)'),
        ),
    ]
