# Generated by Django 3.2.17 on 2024-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0044_alter_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='clipboard',
            field=models.TextField(blank=True, default='', help_text='Google-sheets compliant copy to clipboard for the puzzle', null=True, verbose_name='Clipboard'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='clipboard_remote',
            field=models.TextField(blank=True, default='', help_text='Google-sheets compliant copy to clipboard for the puzzle for remote teams', null=True, verbose_name='Remote Clipboard'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='Markdown-compliant solution to the puzzle.', null=True, verbose_name='Solution'),
        ),
    ]
