# Generated by Django 3.2.17 on 2024-04-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0045_auto_20240408_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorylineUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyline', models.SlugField(verbose_name='Storyline Slug (in frontend)')),
                ('unlock_datetime', models.DateTimeField(verbose_name='Unlock datetime')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'storyline unlock',
                'verbose_name_plural': 'storyline unlocks',
                'unique_together': {('team', 'storyline')},
            },
        ),
        migrations.CreateModel(
            name='MajorCaseCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_datetime', models.DateTimeField(verbose_name='Completed datetime')),
                ('major_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.majorcase', verbose_name='major case')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'major case completed',
                'verbose_name_plural': 'major cases completed',
                'unique_together': {('team', 'major_case')},
            },
        ),
    ]
