# Generated by Django 3.2.17 on 2024-04-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0046_event_eventcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_final_runaround',
            field=models.BooleanField(default=False, verbose_name='Is final runaround'),
        ),
    ]
