# Generated by Django 3.2.17 on 2024-04-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0048_alter_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer'),
        ),
    ]
