# Generated by Django 3.2.17 on 2024-04-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0049_event_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='is_followed_up_on',
            field=models.BooleanField(default=False, verbose_name='Is followed up on'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcompletion',
            unique_together={('team', 'event')},
        ),
    ]
