# Generated by Django 3.2.17 on 2024-04-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0046_majorcasecompleted_storylineunlock'),
        ('puzzles', '0050_auto_20240411_2330'),
    ]

    operations = [
    ]
