# Generated by Django 3.2.17 on 2024-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0051_merge_20240412_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylineunlock',
            name='description',
            field=models.TextField(default='', verbose_name='Storyline Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storylineunlock',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Storyline Title'),
            preserve_default=False,
        ),
    ]
