# Generated by Django 3.2.17 on 2024-04-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0052_auto_20240412_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storylineunlock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storylineunlock',
            name='title',
        ),
    ]
